name: CI
on: pull_request

jobs: 
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - run: npm install
      - run: npm test