name: CI
on: pull_request

jobs: 
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm install
      - run: npm test
